/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-03-27 07:29:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class guitar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head> \r\n");
      out.write("    <title> GZ2H </title>\r\n");
      out.write("	<!-- add icon link -->\r\n");
      out.write("        <link rel = \"icon\" href = \"https://www.nicepng.com/png/full/2-24003_jpg-freeuse-stock-guitar-png-for-free-download.png\" type = \"image/x-icon\">\r\n");
      out.write("      <body>\r\n");
      out.write("	<body background=\"http://hd.wallpaperswide.com/thumbs/white_wooden_slats-t2.jpg\" vlink=\"#000\">\r\n");
      out.write("            <center> \r\n");
      out.write("                 <font size=\"80\" color=\"PURPLE\" ><b>Welcome To Guitar Zero 2 Hero</b></font><br ><br>\r\n");
      out.write("                  <font color=\"WHITE\" size = \"50\" align=\"bottom\"><marquee direction=\"right\" style=\"background:green\" >OFFERS  AVAILABLE  TILL 31st OCT 2021</marquee></font>\r\n");
      out.write("                  <font size=\"5\">Gives You best Deals on Acoustic, Electric and Bass Guitars!</font>\r\n");
      out.write("            </center>\r\n");
      out.write("                     <table style=\"width:100%\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                              <th><img src =\"https://i.ibb.co/Phxctgc/512lk2-UJge-L-SL1500-1.jpg\" width = 365 ></th>\r\n");
      out.write("                              <th><img src =\"https://m.media-amazon.com/images/I/81oK9u3MmCL._AC_SL1500_.jpg\" width = 400 ></th>\r\n");
      out.write("                               <th><img src =\"https://m.media-amazon.com/images/I/71kOMjCSPOL._SL1500_.jpg\" width=400></th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                             <th><b><font size=\"5\" color=\"BROWN\" ><b>Donner DAG-1CE Electric Acoustic Guitar Cutaway 41</b></font><br ><br></b></th>\r\n");
      out.write("                             <th><b><font size=\"5\" color=\"BROWN\" ><b>Ibanez AEG12IINT Acoustic-Electric Guitar</b></font><br ><br></b></th>\r\n");
      out.write("                             <th><b><font size=\"5\" color=\"BROWN\" ><b>Yamaha TRBX174 4-String Electric Bass Guitar</b></font><br ><br></b></th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>₹7,450.00</th>\r\n");
      out.write("                            <th><p style=\"text-decoration: line-through;\">₹49,287</p>₹44,481</th>\r\n");
      out.write("                            <th>₹18,300.00</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("                            <th>Customer rating : ★★★★★</th>\r\n");
      out.write("                            <th>Customer rating : ★★★★☆</th>\r\n");
      out.write("                            <th>Customer rating : ★★☆☆☆</th>\r\n");
      out.write("              \r\n");
      out.write("                         </tr> \r\n");
      out.write("			<tr>\r\n");
      out.write("                            <th>Colour : Natural</th>\r\n");
      out.write("                            <th>Colour : Mahogany Burst</th>\r\n");
      out.write("                            <th>Colour : Dark Blue Metallic</th>\r\n");
      out.write("                         </tr>   \r\n");
      out.write("                         <tr>\r\n");
      out.write("                            <th><a href=\"#Electric Acoustic 1\" target=\"_blank\">Know More>></a></th>\r\n");
      out.write("                            <th><a href=\"#Electric Acoustic 2\" target=\"_blank\">Know More>></a></th>\r\n");
      out.write("                            <th><a href=\"#Bass\" target=\"_blank\">Know More>></a></th>\r\n");
      out.write("                         </tr> \r\n");
      out.write("			 <tr>\r\n");
      out.write("                            <th><a href=\"https://www.amazon.in/Donner-DAG-1CE-Electric-Acoustic-Full-size/dp/B0784GSY7P\" target=\"_blank\">Buy at Amazon</a></th>\r\n");
      out.write("                            <th><a href=\"https://www.bajaao.com/products/ibanez-aeg12ii-acoustic-electric-guitar\" target=\"_blank\">Buy at Bajaoo.com</a></th>\r\n");
      out.write("                            <th><a href=\"https://www.amazon.in/Yamaha-TRBX174-4-String-Electric-Guitar/dp/B00GOE82N8\" target=\"_blank\">Buy at Amazon</a></th>\r\n");
      out.write("                         </tr>     \r\n");
      out.write("                     </table>\r\n");
      out.write("                  <br><br><br><br><br><br><br>\r\n");
      out.write(" 		<center>\r\n");
      out.write("                         <a id=\"#Electric Acoustic 1\"></a><br><br>\r\n");
      out.write("                   	 <font size=\"20\" color=\"BLUE\" ><b>Donner DAG-1CE Electric Acoustic Guitar Cutaway 41</b></font><br ><br>\r\n");
      out.write("			 <th><a size=\"20\" href=\"https://www.amazon.in/Donner-DAG-1CE-Electric-Acoustic-Full-size/dp/B0784GSY7P\">Buy at Amazon</a></th>\r\n");
      out.write("                         <img src =\"https://m.media-amazon.com/images/I/71ozKECfDpS._SL1500_.jpg\" width = 800 ><br>\r\n");
      out.write("                         <p><font size=\"80\">About the Donner DAG-1CE Electric Acoustic Guitar:</font></p>\r\n");
      out.write("                         <p> <font size=\"5\">- Full-size 41 inch cutaway dreadnought body for full and vibrant tone, suited for all styles of music.</p>\r\n");
      out.write("			 <p> <font size=\"5\">- Right-hand design, spruce top and mahogany back and sides bring you richer and brighter sound.</p>\r\n");
      out.write("			 <p> <font size=\"5\">- Built-in preamp for amplified use with volume control, 3 band EQ: bass, mid and treble, integrated tuner for fast and easy tuning.</p>\r\n");
      out.write("                         <br><br>\r\n");
      out.write("                         <p><font size=\"80\">Guitar in detail specifications</font></p>\r\n");
      out.write("                    </center>\r\n");
      out.write("\r\n");
      out.write("              <table style=\"width:100%\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                      <th><img src=\"https://m.media-amazon.com/images/I/71hP36hH-QL._SL1500_.jpg\" width =500 ></th>\r\n");
      out.write("                      <th><img src=\"https://m.media-amazon.com/images/I/71trBRSVcpL._SL1500_.jpg\" width =500 ></th>\r\n");
      out.write("                      <th><img src=\"https://m.media-amazon.com/images/I/71-OZITLYzL._SL1500_.jpg\" width =500 ></th>\r\n");
      out.write("                 </tr> \r\n");
      out.write("                 <tr>\r\n");
      out.write("                     <th><b><font size=\"5\">Supports Multiple Devices</font></b></th>\r\n");
      out.write("                     <th><b><font size=\"5\">Sophisticated Design</font></b></th>  \r\n");
      out.write("                     <th> <b><font size=\"5\">Donner 18:1 Gears</font></th>\r\n");
      out.write("                 </tr>\r\n");
      out.write("             </table>\r\n");
      out.write("             <br><br><br><br><br>\r\n");
      out.write("<!-- Ibanez AEG12IINT Acoustic-Electric Guitar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                     <center>\r\n");
      out.write("                         <a id=\"Electric Acoustic 2\"></a><br><br>\r\n");
      out.write("                   	 <font size=\"20\" color=\"RED\" ><b>Ibanez AEG12IINT Acoustic-Electric Guitar</b></font><br ><br>\r\n");
      out.write("                         <img src =\"https://images.reverb.com/image/upload/s--t2AIu3_U--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1498673675/qbmajfllsrws8lpbltmm.jpg\" width = 800 ><br>\r\n");
      out.write("                         <p><font size=\"80\">About the Ibanez AEG12IINT Acoustic-Electric Guitar:</font></p>\r\n");
      out.write("                         <p> <font size=\"5\">- Mahogany top, back and sides</p>\r\n");
      out.write("			 <p> <font size=\"5\">- High-quality Fishman Sonicore pickups</p>\r\n");
      out.write("			 <p> <font size=\"5\">- Ibanez AEQ-SP1 Preamps</p>\r\n");
      out.write("                         <br><br>\r\n");
      out.write("                         <p><font size=\"80\">Guitar in detail specifications</font></p>\r\n");
      out.write("                    </center>\r\n");
      out.write("\r\n");
      out.write("              <table style=\"width:100%\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                      <th><img src=\"https://m.media-amazon.com/images/I/81br5E5GxVL._AC_SL1500_.jpg\" width =300 ></th>\r\n");
      out.write("                      <th><img src=\"https://m.media-amazon.com/images/I/81KdK1SUrmL._AC_SL1500_.jpg\" width =300 ></th>\r\n");
      out.write("                      <th><img src=\"https://m.media-amazon.com/images/I/81T5xGLQLjL._AC_SL1500_.jpg\" width =300 ></th>\r\n");
      out.write("                 </tr> \r\n");
      out.write("                 <tr>\r\n");
      out.write("                     <th><b><font size=\"5\">Easy playability, classic solid and sunburst finishes.</font></b></th>\r\n");
      out.write("                     <th><b><font size=\"5\">SAEG body Bracing: X Bracing Top: Mahogany Back & sides</font></b></th>  \r\n");
      out.write("                     <th> <b><font size=\"5\">Mahogany Back & Sides Neck: Mahogany neck (satin finish) </font></th>\r\n");
      out.write("                 </tr>\r\n");
      out.write("             </table>\r\n");
      out.write("	     <br><br><br><br><br>\r\n");
      out.write("<!-- Yamaha TRBX174 4-String Electric Bass Guitar  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              <center>\r\n");
      out.write("			 <a id=\"Bass\"></a><br><br>\r\n");
      out.write("                   	 <font size=\"20\" color=\"BROWN\" ><b>Yamaha TRBX174 4-String Electric Bass Guitar</b></font><br ><br>\r\n");
      out.write("                         <img src =\"https://m.media-amazon.com/images/I/71JzFacs3tL._SL1500_.jpg\" width = 800 ><br>\r\n");
      out.write("                         <p><font size=\"80\">About the Yamaha TRBX174 4-String Electric Bass Guitar:</font></p>\r\n");
      out.write("                         <p> <font size=\"5\">- Scale length: 34'' (863.6mm) neck: Maple fingerboard: Snorkeling radius: 10'' (250mm)</p>\r\n");
      out.write("			 <p> <font size=\"5\">- Nut width: 40mm body: Alder tuners: Covered bridge: Vintage style pickups: Split coil x 1, single coil x 1</p>\r\n");
      out.write("			 <p> <font size=\"5\">- Vintage style bridge</p>\r\n");
      out.write("                         <br><br>\r\n");
      out.write("                         <p><font size=\"80\">Guitar in detail specifications</font></p>\r\n");
      out.write("                    </center>\r\n");
      out.write("\r\n");
      out.write("              <table style=\"width:100%\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                      <th><img src=\"https://m.media-amazon.com/images/I/61k1U2xoDRL._SL1000_.jpg\" width =300 ></th>\r\n");
      out.write("                      <th><img src=\"https://m.media-amazon.com/images/I/61VlOnw-eAL._SL1000_.jpg\" width =300 ></th>\r\n");
      out.write("                      <th><img src=\"https://m.media-amazon.com/images/I/41ID6QuA4JL.jpg\" width =300 ></th>\r\n");
      out.write("                 </tr> \r\n");
      out.write("                 <tr>\r\n");
      out.write("                     <th><b><font size=\"5\">Advanced design, precision engineering</font></b></th>\r\n");
      out.write("                     <th><b><font size=\"5\">Perfect Finish</font></b></th>  \r\n");
      out.write("                     <th> <b><font size=\"5\">Comes with Yamaha Tunner application.</font></th>\r\n");
      out.write("                 </tr>\r\n");
      out.write("             </table>\r\n");
      out.write("            <br><br><br><br><br>\r\n");
      out.write("                    \r\n");
      out.write("      </body>\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
